/*
 Navicat Premium Dump SQL

 Source Server         : AveMujica
 Source Server Type    : PostgreSQL
 Source Server Version : 160010 (160010)
 Source Host           : 172.24.122.36:5432
 Source Catalog        : postgres
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160010 (160010)
 File Encoding         : 65001

 Date: 17/09/2025 18:38:08
*/


-- ----------------------------
-- Sequence structure for am_account_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."am_account_id_seq";
CREATE SEQUENCE "public"."am_account_id_seq" 
INCREMENT 1
MINVALUE  1000000
MAXVALUE 999999999
START 1000000
CACHE 1;

-- ----------------------------
-- Sequence structure for am_answer_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."am_answer_id_seq";
CREATE SEQUENCE "public"."am_answer_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 10000000
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for am_question_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."am_question_id_seq";
CREATE SEQUENCE "public"."am_question_id_seq" 
INCREMENT 1
MINVALUE  100
MAXVALUE 10000
START 100
CACHE 1;

-- ----------------------------
-- Sequence structure for am_question_score_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."am_question_score_id_seq";
CREATE SEQUENCE "public"."am_question_score_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 1000000
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for am_score_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."am_score_id_seq";
CREATE SEQUENCE "public"."am_score_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 1000000
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for am_submit_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."am_submit_id_seq";
CREATE SEQUENCE "public"."am_submit_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 10000000
START 1
CACHE 1;

-- ----------------------------
-- Table structure for am_account
-- ----------------------------
DROP TABLE IF EXISTS "public"."am_account";
CREATE TABLE "public"."am_account" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1000000
MAXVALUE 999999999
START 1000000
CACHE 1
),
  "username" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "password" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "email" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "role" varchar(30) COLLATE "pg_catalog"."default" NOT NULL,
  "register_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
)
;

-- ----------------------------
-- Table structure for am_answer
-- ----------------------------
DROP TABLE IF EXISTS "public"."am_answer";
CREATE TABLE "public"."am_answer" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 10000000
START 1
CACHE 1
),
  "question_id" int4 NOT NULL,
  "flag_answer" varchar(255) COLLATE "pg_catalog"."default",
  "choice_answer" jsonb
)
;

-- ----------------------------
-- Table structure for am_question
-- ----------------------------
DROP TABLE IF EXISTS "public"."am_question";
CREATE TABLE "public"."am_question" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  100
MAXVALUE 10000
START 100
CACHE 1
),
  "type" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "title" json NOT NULL,
  "content" json NOT NULL,
  "origin_score" int4 NOT NULL,
  "deadline" timestamp(6) NOT NULL,
  "current_score" int4 NOT NULL,
  "first_blood" varchar(50) COLLATE "pg_catalog"."default",
  "difficulty" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "question_order" int2 NOT NULL,
  "turn" int2 NOT NULL,
  "direction" varchar(50) COLLATE "pg_catalog"."default"
)
;
COMMENT ON COLUMN "public"."am_question"."id" IS '主键';
COMMENT ON COLUMN "public"."am_question"."first_blood" IS '对应account.username,外键';

-- ----------------------------
-- Table structure for am_question_score
-- ----------------------------
DROP TABLE IF EXISTS "public"."am_question_score";
CREATE TABLE "public"."am_question_score" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 1000000
START 1
CACHE 1
),
  "question_id" int4 NOT NULL,
  "origin_score" int4 NOT NULL,
  "submit_count" int4 NOT NULL DEFAULT 0,
  "average" int4 NOT NULL DEFAULT 0,
  "std" int4 NOT NULL DEFAULT 0,
  "decline" float4 DEFAULT 1
)
;

-- ----------------------------
-- Table structure for am_score
-- ----------------------------
DROP TABLE IF EXISTS "public"."am_score";
CREATE TABLE "public"."am_score" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 1000000
START 1
CACHE 1
),
  "user_id" int4 NOT NULL,
  "username" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "scores" jsonb,
  "total_score" int4 NOT NULL DEFAULT 0,
  "produced_scores" jsonb,
  "direction_scores" jsonb
)
;

-- ----------------------------
-- Table structure for am_submit
-- ----------------------------
DROP TABLE IF EXISTS "public"."am_submit";
CREATE TABLE "public"."am_submit" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 10000000
START 1
CACHE 1
),
  "user_id" int4 NOT NULL,
  "question_id" int4 NOT NULL,
  "time_record" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "score" int4 NOT NULL DEFAULT 0,
  "count" int4 NOT NULL,
  "file_name" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."am_account_id_seq"
OWNED BY "public"."am_account"."id";
SELECT setval('"public"."am_account_id_seq"', 1111113, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."am_answer_id_seq"
OWNED BY "public"."am_answer"."id";
SELECT setval('"public"."am_answer_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."am_question_id_seq"
OWNED BY "public"."am_question"."id";
SELECT setval('"public"."am_question_id_seq"', 118, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."am_question_score_id_seq"
OWNED BY "public"."am_question_score"."id";
SELECT setval('"public"."am_question_score_id_seq"', 2, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."am_score_id_seq"
OWNED BY "public"."am_score"."id";
SELECT setval('"public"."am_score_id_seq"', 3, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."am_submit_id_seq"
OWNED BY "public"."am_submit"."id";
SELECT setval('"public"."am_submit_id_seq"', 9, true);

-- ----------------------------
-- Primary Key structure for table am_account
-- ----------------------------
ALTER TABLE "public"."am_account" ADD CONSTRAINT "am_account_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table am_answer
-- ----------------------------
ALTER TABLE "public"."am_answer" ADD CONSTRAINT "am_answer_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table am_question
-- ----------------------------
ALTER TABLE "public"."am_question" ADD CONSTRAINT "am_question_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table am_question_score
-- ----------------------------
ALTER TABLE "public"."am_question_score" ADD CONSTRAINT "am_question_score_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table am_score
-- ----------------------------
CREATE INDEX "direction_scores_gin" ON "public"."am_score" USING gin (
  "direction_scores" "pg_catalog"."jsonb_ops"
) WITH (GIN_PENDING_LIST_LIMIT = 64);
CREATE INDEX "total_b-tree" ON "public"."am_score" USING btree (
  "total_score" "pg_catalog"."int4_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table am_score
-- ----------------------------
ALTER TABLE "public"."am_score" ADD CONSTRAINT "am_score_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table am_submit
-- ----------------------------
ALTER TABLE "public"."am_submit" ADD CONSTRAINT "am_submit_pkey" PRIMARY KEY ("id");
