spring:
  application:
    name: Entrance
  datasource:
    url: jdbc:postgresql://172.24.122.36:5432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.163.com
    username: 17264278094@163.com
    password: KBpgnSzSiQtmya9P
  rabbitmq:
    addresses: 172.24.122.36
    username: admin
    password: 123456
    virtual-host: test
  web:
    verify:
      mail-limit: 60
    flow:
      period: 5
      limit: 100
      block: 30
#    cors:
#      origin: '*'
#      credentials: false
#      methods: '*'
  security:
    jwt:
      key: 'AveMujica'
      expire: 72
      limit:
        base: 20
        upgrade: 200
        frequency: 30
    filter:
      order: -100
server:
  port: 8080
  servlet:
    context-path: /AveMujica


