spring:
  application:
    name: Entrance
  datasource:
    url: jdbc:postgresql://172.24.122.36:5432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.163.com
    username: 17264278094@163.com
    password: KBpgnSzSiQtmya9P
  rabbitmq:
    addresses: 172.24.122.36
    username: admin
    password: 123456
    virtual-host: test
  web:
    submit:
      limit: 5
    file:
      limit: 60
    verify:
      mail-limit: 60
    flow:
      period: 5
      limit: 100
      block: 30
#    cors:
#      origin: '*'
#      credentials: false
#      methods: '*'
  security:
    jwt:
      key: 'AveMujica'
      expire: 72
      limit:
        base: 20
        upgrade: 200
        frequency: 30
    filter:
      order: -100

  data:
    redis:
      host: 172.24.122.36
      port: 6379
      database: 0
      timeout: 2000ms
      password: xyxyxy
  cache:
    cache-names: questionCache
    caffeine:
      spec: maximumSize=5000,expireAfterWrite=60s  # L1 命中 120s 默认配置

server:
  port: 8080
  servlet:
    context-path: /AveMujica

nonce:
  expire:
    seconds: 3600

minio:
  endpoint: http://172.24.122.36:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: submit
  presign-expire-seconds: 6000  # 预签名URL有效期(秒)

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

custom:
  cache:
    redis-ttl-seconds: 300       # L2 主 TTL（再加抖动）
    jitter-seconds: 60
    bloom:
      name: bf:question