spring:
  application:
    name: Entrance
  datasource:
    url: jdbc:postgresql://172.24.122.36:5432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.163.com
    username: 17264278094@163.com
    password: KBpgnSzSiQtmya9P
  rabbitmq:
    addresses: 172.24.122.36
    username: admin
    password: 123456
    virtual-host: test
  web:
    submit:
      limit: 5
    file:
      limit: 60
    verify:
      mail-limit: 60
    flow:
      period: 5
      limit: 100
      block: 30
  security:
    jwt:
      key: 'AveMujica'
      expire: 72
      limit:
        base: 20
        upgrade: 200
        frequency: 30
    filter:
      order: -100

  data:
    redis:
      host: 172.24.122.36
      port: 6379
      database: 0
      timeout: 2000ms
      password: xyxyxy
  cache:
    cache-names: questionCache
    caffeine:
      spec: maximumSize=5000,expireAfterWrite=60s

server:
  port: 8080
  servlet:
    context-path: /AveMujica

nonce:
  expire:
    seconds: 3600

minio:
  endpoint: http://172.24.122.36:9000
  bucket: submit
  presign-expire-seconds: 6000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

custom:
  cache:
    redis-ttl-seconds: 300
    jitter-seconds: 60
    bloom:
      name: bf:question